<template>
  <div class="min-h-screen w-full bg-slate-50 text-slate-900 font-sans overflow-x-hidden selection:bg-purple-200">

    <!-- Hero Section -->
    <section class="relative pt-32 pb-20 lg:pt-48 lg:pb-32 px-6">
      <!-- Background Blobs -->
      <div class="absolute top-0 left-1/2 -translate-x-1/2 w-full h-full overflow-hidden -z-10 pointer-events-none">
        <div class="absolute top-[-10%] left-[-10%] w-[40rem] h-[40rem] bg-purple-200/40 rounded-full blur-3xl mix-blend-multiply animate-blob"></div>
        <div class="absolute top-[-10%] right-[-10%] w-[40rem] h-[40rem] bg-yellow-200/40 rounded-full blur-3xl mix-blend-multiply animate-blob animation-delay-2000"></div>
        <div class="absolute bottom-[-20%] left-[20%] w-[40rem] h-[40rem] bg-pink-200/40 rounded-full blur-3xl mix-blend-multiply animate-blob animation-delay-4000"></div>
      </div>

      <div class="max-w-4xl mx-auto text-center">
        <div v-motion :initial="{ opacity: 0, y: 20 }" :enter="{ opacity: 1, y: 0 }" :delay="200" class="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-purple-50 border border-purple-100 text-purple-700 text-xs font-semibold uppercase tracking-wide mb-6">
          <span class="w-2 h-2 rounded-full bg-purple-500 animate-pulse"></span>
          v0.18 is now live
        </div>
        
        <h1 v-motion :initial="{ opacity: 0, y: 20 }" :enter="{ opacity: 1, y: 0 }" :delay="300" class="text-5xl md:text-7xl font-extrabold tracking-tight text-slate-900 mb-8 leading-tight">
          Connect your Web <br />
          <span class="text-transparent bg-clip-text bg-gradient-to-r from-purple-600 to-indigo-600">
            Without Boundaries.
          </span>
        </h1>
        
        <p v-motion :initial="{ opacity: 0, y: 20 }" :enter="{ opacity: 1, y: 0 }" :delay="400" class="text-lg md:text-xl text-slate-600 mb-4 max-w-2xl mx-auto leading-relaxed">
          TrojoNetworks empowers you to build interconnected digital spaces. 
          Create public or private networks, manage permissions, and unify user identities across the entire ecosystem.
        </p>

        <p v-motion :initial="{ opacity: 0, y: 20 }" :enter="{ opacity: 1, y: 0 }" :delay="400" class="text-sm md:text-md text-slate-600 mb-10 max-w-md mx-auto leading-relaxed">
          The home and about page are simply generated by AI. None of this should be believed directly, but it sure looks nice.
        </p>
        
        <div v-motion :initial="{ opacity: 0, y: 20 }" :enter="{ opacity: 1, y: 0 }" :delay="500" class="flex flex-col sm:flex-row items-center justify-center gap-4">
          <button class="w-full sm:w-auto px-8 py-4 rounded-full bg-purple-600 text-white font-semibold hover:bg-purple-700 hover:shadow-lg hover:shadow-purple-500/30 transition transform hover:-translate-y-0.5">
            Start Building
          </button>
          <button class="w-full sm:w-auto px-8 py-4 rounded-full bg-white border border-slate-200 text-slate-700 font-semibold hover:bg-slate-50 hover:border-slate-300 transition">
            View Documentation
          </button>
        </div>
      </div>
    </section>

    <!-- Features Grid -->
    <section class="py-20 px-6 bg-white/50 backdrop-blur-sm">
      <div class="max-w-7xl mx-auto">
        <div class="grid md:grid-cols-3 gap-8">
          <!-- Feature 1 -->
          <div v-motion-slide-visible-once-bottom class="group p-8 rounded-3xl bg-white border border-slate-100 shadow-xl shadow-slate-200/50 hover:shadow-2xl hover:shadow-purple-500/10 transition duration-300">
            <div class="w-12 h-12 rounded-2xl bg-purple-100 text-purple-600 flex items-center justify-center mb-6 group-hover:scale-110 transition">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
              </svg>
            </div>
            <h3 class="text-xl font-bold mb-3 text-slate-900">Network Management</h3>
            <p class="text-slate-600 leading-relaxed">
              Create and manage public or private networks with granular permission controls. You decide who joins and what they can do.
            </p>
          </div>

          <!-- Feature 2 -->
          <div v-motion-slide-visible-once-bottom :delay="100" class="group p-8 rounded-3xl bg-white border border-slate-100 shadow-xl shadow-slate-200/50 hover:shadow-2xl hover:shadow-purple-500/10 transition duration-300">
            <div class="w-12 h-12 rounded-2xl bg-indigo-100 text-indigo-600 flex items-center justify-center mb-6 group-hover:scale-110 transition">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
              </svg>
            </div>
            <h3 class="text-xl font-bold mb-3 text-slate-900">Unified Identity</h3>
            <p class="text-slate-600 leading-relaxed">
              Say goodbye to fragmented accounts. Users carry their identity, reputation, and data seamlessly across all connected networks.
            </p>
          </div>

          <!-- Feature 3 -->
          <div v-motion-slide-visible-once-bottom :delay="200" class="group p-8 rounded-3xl bg-white border border-slate-100 shadow-xl shadow-slate-200/50 hover:shadow-2xl hover:shadow-purple-500/10 transition duration-300">
            <div class="w-12 h-12 rounded-2xl bg-pink-100 text-pink-600 flex items-center justify-center mb-6 group-hover:scale-110 transition">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 4a2 2 0 114 0v1a1 1 0 001 1h3a1 1 0 011 1v3a1 1 0 01-1 1h-1a2 2 0 100 4h1a1 1 0 011 1v3a1 1 0 01-1 1h-3a1 1 0 01-1-1v-1a2 2 0 10-4 0v1a1 1 0 01-1 1H7a1 1 0 01-1-1v-3a1 1 0 00-1-1H4a2 2 0 110-4h1a1 1 0 001-1V7a1 1 0 011-1h3a1 1 0 001-1V4z" />
              </svg>
            </div>
            <h3 class="text-xl font-bold mb-3 text-slate-900">Fully Customizable</h3>
            <p class="text-slate-600 leading-relaxed">
              Tailor the experience to your needs. From content structure to UI themes, every aspect of your network is under your control.
            </p>
          </div>
        </div>
      </div>
    </section>

  </div>
</template>

<script setup lang="ts">
// No specific script logic needed for this static presentation, 
// but v-motion directives are used in template.
</script>

<style scoped>
.animate-blob {
  animation: blob 7s infinite;
}
.animation-delay-2000 {
  animation-delay: 2s;
}
.animation-delay-4000 {
  animation-delay: 4s;
}
@keyframes blob {
  0% { transform: translate(0px, 0px) scale(1); }
  33% { transform: translate(30px, -50px) scale(1.1); }
  66% { transform: translate(-20px, 20px) scale(0.9); }
  100% { transform: translate(0px, 0px) scale(1); }
}
</style>
