<template>
  <div
    class="min-h-screen w-full overflow-x-hidden bg-slate-50 font-sans text-slate-900 selection:bg-purple-200"
  >
    <!-- Hero Section -->
    <section class="relative px-6 pb-20 pt-32 lg:pb-32 lg:pt-48">
      <!-- Background Blobs -->
      <div
        class="pointer-events-none absolute left-1/2 top-0 -z-10 h-full w-full -translate-x-1/2 overflow-hidden"
      >
        <div
          class="animate-blob absolute left-[-10%] top-[-10%] h-[40rem] w-[40rem] rounded-full bg-purple-200/40 mix-blend-multiply blur-3xl"
        ></div>
        <div
          class="animate-blob animation-delay-2000 absolute right-[-10%] top-[-10%] h-[40rem] w-[40rem] rounded-full bg-yellow-200/40 mix-blend-multiply blur-3xl"
        ></div>
        <div
          class="animate-blob animation-delay-4000 absolute bottom-[-20%] left-[20%] h-[40rem] w-[40rem] rounded-full bg-pink-200/40 mix-blend-multiply blur-3xl"
        ></div>
      </div>

      <div class="mx-auto max-w-4xl text-center">
        <div
          v-motion
          :initial="{ opacity: 0, y: 20 }"
          :enter="{ opacity: 1, y: 0 }"
          :delay="200"
          class="mb-6 inline-flex items-center gap-2 rounded-full border border-purple-100 bg-purple-50 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-purple-700"
        >
          <span class="h-2 w-2 animate-pulse rounded-full bg-purple-500"></span>
          v0.21 is now live
        </div>

        <h1
          v-motion
          :initial="{ opacity: 0, y: 20 }"
          :enter="{ opacity: 1, y: 0 }"
          :delay="300"
          class="mb-8 text-5xl font-extrabold leading-tight tracking-tight text-slate-900 md:text-7xl"
        >
          Connect your Web <br />
          <span
            class="bg-gradient-to-r from-purple-600 to-indigo-600 bg-clip-text text-transparent"
          >
            Without Boundaries.
          </span>
        </h1>

        <p
          v-motion
          :initial="{ opacity: 0, y: 20 }"
          :enter="{ opacity: 1, y: 0 }"
          :delay="400"
          class="mx-auto mb-4 max-w-2xl text-lg leading-relaxed text-slate-600 md:text-xl"
        >
          TrojoNetworks empowers you to build interconnected digital spaces. Create public or
          private networks, manage permissions, and unify user identities across the entire
          ecosystem.
        </p>

        <p
          v-motion
          :initial="{ opacity: 0, y: 20 }"
          :enter="{ opacity: 1, y: 0 }"
          :delay="400"
          class="md:text-md mx-auto mb-10 max-w-md text-sm leading-relaxed text-slate-600"
        >
          The home and about page are simply generated by AI. None of this should be believed
          directly, but it sure looks nice.
        </p>

        <div
          v-motion
          :initial="{ opacity: 0, y: 20 }"
          :enter="{ opacity: 1, y: 0 }"
          :delay="500"
          class="flex flex-col items-center justify-center gap-4 sm:flex-row"
        >
          <button
            class="w-full transform rounded-full bg-purple-600 px-8 py-4 font-semibold text-white transition hover:-translate-y-0.5 hover:bg-purple-700 hover:shadow-lg hover:shadow-purple-500/30 sm:w-auto"
          >
            Start Building
          </button>
          <button
            class="w-full rounded-full border border-slate-200 bg-white px-8 py-4 font-semibold text-slate-700 transition hover:border-slate-300 hover:bg-slate-50 sm:w-auto"
          >
            View Documentation
          </button>
        </div>
      </div>
    </section>

    <!-- Features Grid -->
    <section class="bg-white/50 px-6 py-20 backdrop-blur-sm">
      <div class="mx-auto max-w-7xl">
        <div class="grid gap-8 md:grid-cols-3">
          <!-- Feature 1 -->
          <div
            v-motion-slide-visible-once-bottom
            class="group rounded-3xl border border-slate-100 bg-white p-8 shadow-xl shadow-slate-200/50 transition duration-300 hover:shadow-2xl hover:shadow-purple-500/10"
          >
            <div
              class="mb-6 flex h-12 w-12 items-center justify-center rounded-2xl bg-purple-100 text-purple-600 transition group-hover:scale-110"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-6 w-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"
                />
              </svg>
            </div>
            <h3 class="mb-3 text-xl font-bold text-slate-900">Network Management</h3>
            <p class="leading-relaxed text-slate-600">
              Create and manage public or private networks with granular permission controls. You
              decide who joins and what they can do.
            </p>
          </div>

          <!-- Feature 2 -->
          <div
            v-motion-slide-visible-once-bottom
            :delay="100"
            class="group rounded-3xl border border-slate-100 bg-white p-8 shadow-xl shadow-slate-200/50 transition duration-300 hover:shadow-2xl hover:shadow-purple-500/10"
          >
            <div
              class="mb-6 flex h-12 w-12 items-center justify-center rounded-2xl bg-indigo-100 text-indigo-600 transition group-hover:scale-110"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-6 w-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"
                />
              </svg>
            </div>
            <h3 class="mb-3 text-xl font-bold text-slate-900">Unified Identity</h3>
            <p class="leading-relaxed text-slate-600">
              Say goodbye to fragmented accounts. Users carry their identity, reputation, and data
              seamlessly across all connected networks.
            </p>
          </div>

          <!-- Feature 3 -->
          <div
            v-motion-slide-visible-once-bottom
            :delay="200"
            class="group rounded-3xl border border-slate-100 bg-white p-8 shadow-xl shadow-slate-200/50 transition duration-300 hover:shadow-2xl hover:shadow-purple-500/10"
          >
            <div
              class="mb-6 flex h-12 w-12 items-center justify-center rounded-2xl bg-pink-100 text-pink-600 transition group-hover:scale-110"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-6 w-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M11 4a2 2 0 114 0v1a1 1 0 001 1h3a1 1 0 011 1v3a1 1 0 01-1 1h-1a2 2 0 100 4h1a1 1 0 011 1v3a1 1 0 01-1 1h-3a1 1 0 01-1-1v-1a2 2 0 10-4 0v1a1 1 0 01-1 1H7a1 1 0 01-1-1v-3a1 1 0 00-1-1H4a2 2 0 110-4h1a1 1 0 001-1V7a1 1 0 011-1h3a1 1 0 001-1V4z"
                />
              </svg>
            </div>
            <h3 class="mb-3 text-xl font-bold text-slate-900">Fully Customizable</h3>
            <p class="leading-relaxed text-slate-600">
              Tailor the experience to your needs. From content structure to UI themes, every aspect
              of your network is under your control.
            </p>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
// No specific script logic needed for this static presentation,
// but v-motion directives are used in template.
</script>

<style scoped>
.animate-blob {
  animation: blob 7s infinite;
}
.animation-delay-2000 {
  animation-delay: 2s;
}
.animation-delay-4000 {
  animation-delay: 4s;
}
@keyframes blob {
  0% {
    transform: translate(0px, 0px) scale(1);
  }
  33% {
    transform: translate(30px, -50px) scale(1.1);
  }
  66% {
    transform: translate(-20px, 20px) scale(0.9);
  }
  100% {
    transform: translate(0px, 0px) scale(1);
  }
}
</style>
